[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name            = "backendb"
version         = "0.1.0"
description     = "Add your description here"
requires-python = ">=3.12"

dependencies = [
    "aiosqlite>=0.21.0",
    "email-validator>=2.2.0",
    "fastapi-users[sqlalchemy]>=14.0.1",
    "fastapi[standard]>=0.116.1", # extra называется standard
    "passlib[bcrypt]>=1.7.4",
    "pydantic>=2",
    "pydantic-settings>=2.10.1",
    "pytest>=8.4.1",
    "python-jose[cryptography]>=3.5.0",
    "sqlalchemy>=2",
    "uvicorn>=0.35.0",
]

# --- всё, секция [project] закончилась. ---

[tool.setuptools]
package-dir = {"" = "src"}          # корень пакетов находится в ./src

[tool.setuptools.packages.find]
where = ["src"]                     # искать пакеты только в этой папке
